### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by leonardoRC** [konnogatto/SwitchDisplay#1]
I'm trying to use this amazing extension but nothin happens.
I just put the file into the playnite, and configure monitor on fullscreen monitor settings,
Need to make some additional configurations?

**Comment by konnogatto** [comment]
Are you using Playnite in a full-screen mode? It only works this way. Does anything happens on start? Any kind of display blinking? It should always attempt to switch as long as display was set and it's not primary already.

**Comment by leonardoRC** [comment]
Are you using Playnite in a full-screen mode?
Yes
Does anything happens on start? Any kind of display blinking?
No
It should always attempt to switch as long as the display was set and it's not primary already.
yes, It's exactly that the point.
Are you using Nvidia drivers? windows 10?

how can I debug this extension?

**Comment by konnogatto** [comment]
> Are you using Nvidia drivers? windows 10?

Windows 10 with Radeon, but it shouldn't matter since it uses standard windows api

Does your log at %appdata%\Playnite\playnite.log has a string "Error setting primary display: Your display DeviceName"?

**Comment by leonardoRC** [comment]
Hello good news, I formatted my computer and updated my graphics card drivers for the version 451,67 using Nvidia gtx1050ti, after reinstalling the application and the extension everything is working perfectly
Thanks for your attention and for this amazing extension
