### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by ATNewHope** [konnogatto/SwitchDisplay#15]
This is an awesome extension! Please consider adding localization support. Thank you!

**Comment by konnogatto** [comment]
It has like 10 words that you see only once, i don't think that it's necessary

**Comment by ATNewHope** [comment]
> It has like 10 words that you see only once, i don't think that it's necessary

Well, it's not necessary for me. However, if there is a useful extension I want to tell my friends, and they say, "what? No Chinese? Nah" then every "10 words" could be a huge wall on my way to promote Playnite and its extensions, and non-English users even don't know how awesome they are, let alone support them.

P.S. What I meant is adding a "translate" link to help in translation on Crowdin, which is free for public project like this one. Volunteers on it like me, will help translate your extension(s).

**Comment by konnogatto** [comment]
I added basic localization support for generic pull requests, i will look into crowdin integration later
