### ISSUE TITLE
Extension can't be installed in Playnite 8

### ISSUE THREAD

**Issue by darklinkpower** [konnogatto/SwitchDisplay#3]
Playnite 8 requires an `Id` property in extension manifests or will refuse to install

https://playnite.link/docs/playnite8/changelog.html
https://playnite.link/docs/playnite8/tutorials/extensionsManifest.html

![imagen](https://user-images.githubusercontent.com/1389286/96120923-e7281d00-0eb4-11eb-9a25-11796d1bff47.png)

**Comment by konnogatto** [comment]
Fixed, you can grab new version from releases

**Comment by darklinkpower** [comment]
I noticed that the forums still link to the previous version
![imagen](https://user-images.githubusercontent.com/1389286/96288072-782bf080-0fa8-11eb-9016-0bef9cada224.png)

https://playnite.link/forum/thread-265.html

I think you should link to https://github.com/konnogatto/SwitchDisplay/releases/latest or post the latest pext file there

**Comment by konnogatto** [comment]
I edited the forum post
