### ISSUE TITLE
Line at top of screen

### ISSUE THREAD

**Issue by MrDrumline** [konnogatto/SwitchDisplay#4]
When exiting a game, I get a strange line white line at the top of my screen in Playnite:

![whiteline](https://user-images.githubusercontent.com/6879719/101073889-18949f00-356e-11eb-87df-bd90999f9e42.png)

Additionally, when ingame I get a single line of pixels at the top of the screen that appear to be the wrong color, and they change color when things happen on screen. It's not an issue with the display or my graphics card, that row of pixels works fine when the SwitchDisplay extension is disabled, and I don't get the white line in Playnite after either. I wonder if fullscreen isn't being engaged properly or something?

I'm using a 1440p monitor as a primary display, and a 4K TV as a secondary.

**Comment by MrDrumline** [comment]
Pressing Alt+Enter twice to un and re-fullscreen the application before launching a game seems to prevent the issue from happening after a game is exited. I wonder if it's not properly scaling the borderless fullscreen mode Playnite uses, or something?

**Comment by MrDrumline** [comment]
Also worth noting that before I cycle Alt-Enter, part of the screen also doesn't fit fully onto my 4K display and peeks over into the left side of my main one:
![cropissue](https://user-images.githubusercontent.com/6879719/101079290-492c0700-3575-11eb-9e75-0313b7336d20.png)

Again, this only happens when the SwitchDisplay extension is enabled.

**Comment by konnogatto** [comment]
This extension only uses windows api to switch display same way as you can do in windows setting, there is absolutely nothing i can do. This means that Playnite itself doesn't handle display change correctly.
