### ISSUE TITLE
Display does not switch

### ISSUE THREAD

**Issue by Peaj** [konnogatto/SwitchDisplay#5]
When launching Playnite fullscreen mode the main display does not switch and the fullscreen mode is displayed on my PC screen instead of the TV.
The Playnite window seems to blink a breif moment on the TV screen (HISENSE) before popping up on the PC monitor (LG ULTRAWIDE)
The audio device switches correctly.

These are my settings:
![grafik](https://user-images.githubusercontent.com/3155116/123562348-8fb1af00-d7ae-11eb-9864-2bc8d6c15432.png)

I did not find any error related to displays in the playnite log.

**Comment by konnogatto** [comment]
Sorry, i cannot test on Nvidia's GPUs. I have a feeling that Nvidia's driver/software enforces display configuration on switch attempt.

**Comment by Peaj** [comment]
Could be possible. Steam Big Picture mode does switch displays properly though.
Is there any way I could debug the extension?

**Comment by Peaj** [comment]
I managed to debug the extension and step through it. It seems like SwitchPrimaryDisplay works just fine.
When launching the fullescreen.exe SwitchPrimaryDisplay returns true and at the end of OnApplicationStarted the main display has been switched and Playnite pops up on the TV (although not fullscreen). 

If the code continues to run after that point the window somehow gets moved to the other screen.
I could not figure out why or where exactly this happens yet.
The main display does stay switched as intended and only changes back after quitting Playnite.
It is only the Playnite window getting moved back to the wrong screen.

**Comment by konnogatto** [comment]
Have you set Target Monitor in the fullscreen Playnite's own settings to your TV? It's separated from what extension does.

**Comment by Peaj** [comment]
No I didn't. Didn't even know the fullscreen mode had separate settings.
Also having a target display option seems pretty useless without switching the main display...
Sry for the inconvenience and thx for the help and this extension 👍
