### ISSUE TITLE
Displays not showing up in settings when using Windows 11

### ISSUE THREAD

**Issue by WowIMadeThis** [konnogatto/SwitchDisplay#6]
I'm using the latest Windows 11 preview build, and the list of available displays in the plugin settings is empty (I have a monitor and a TV connected). 

The list of audio devices is populated as expected.

I'm guessing some kind of change in Windows 11 is the cause of this.

I'm not a programmer, but let me now if I can be of any help in figuring this out.

**Comment by brotherko** [comment]
I am currently using Windows 11 too but doesn't have any issues as u mentioned
