### ISSUE TITLE
[Question] Will you publish this extension in P9 extension downloader?

### ISSUE THREAD

**Issue by ferrazpedro** [konnogatto/SwitchDisplay#9]
Basically the question is in the title. Thanks for the awesome extension!

**Comment by sharkusmanch** [comment]
Pre-requisite manifest file was added in https://github.com/konnogatto/SwitchDisplay/pull/8

PR to add to addon repo - https://github.com/JosefNemec/PlayniteAddonDatabase/pull/50

**Comment by sharkusmanch** [comment]
Now available in the addon browser under generic
